export const studentActionType = {
  FETCH_DATA: "FETCH_DATA",
  EDIT_USER: "EDIT_USER",
  REMOVE_USER_BY_ID: "REMOVE_USER_BY_ID",
  ADD_STUDENT: "ADD_STUDENT",
  OLD_USER: "OLD_USER",
  OPEN_MODAL: "OPEN_MODAL",
  SEARCH: "SEARCH",
};
